AllCops:
  Exclude:
    - "vendor/**/*"
    - "demo/vendor/**/*"
  DisplayCopNames: true

Layout/ArgumentAlignment:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 50

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/EmptyLineAfterGuardClause:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 5

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SymbolArray:
  Enabled: false
